name: CI
on:
  push: # test + build + release
    branches: [ master ]
  pull_request: # test + build
    branches: [ master ]
  release: # test + build + release
    types: [ published ]
env:
  DC1: ldc-1.28.0
  DC2: dmd-2.098.0
  LINKFLAGS: -L/NODEFAULTLIB:libcmt -L/NODEFAULTLIB:libvcruntime
  LIBS: lib/liblz4_static.lib lib/glfw3.lib lib/enet64.lib lib/mdbx.lib lib/mimalloc-static.lib lib/shaderc_combined.lib lib/zstd_static.lib lib/TracyProfiler.lib ntdll.lib User32.lib Advapi32.lib ws2_32.lib winmm.lib gdi32.lib msvcrt.lib
  DEPS: -I=vox/source -I=host

defaults:
  run:
    shell: bash

jobs:
  build-ldc-debug:
    name: LDC debug
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ env.DC1 }}
      - name: Download lib.z7
        run: curl -OLs https://github.com/MrSmith33/voxelman2/releases/download/deps/lib.7z
      - name: Unpack lib.z7
        run: 7z x -ba -bso0 -bsp0 lib.7z
      - name: Try build ldc debug
        run: ldc2 -m64 -g -i host/main.d -of=bin/voxelman.exe $DEPS $LIBS $LINKFLAGS

  build-ldc-release:
    name: LDC release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ env.DC1 }}
      - name: Download lib.z7
        run: curl -OLs https://github.com/MrSmith33/voxelman2/releases/download/deps/lib.7z
      - name: Unpack lib.z7
        run: 7z x -ba -bso0 -bsp0 lib.7z
      - name: Try build release
        run: ldc2 -m64 -O3 -release -boundscheck=off -enable-inlining -mcpu=native -flto=full -i -g host/main.d -of=bin/voxelman.exe $DEPS $LIBS $LINKFLAGS

  build-dmd:
    name: DMD debug
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ env.DC2 }}
      - name: Download libs
        run: |
          curl -OLs https://github.com/MrSmith33/voxelman2/releases/download/deps/lib.7z
          7z x -ba -bso0 -bsp0 lib.7z
      - name: Try build
        run: dmd -m64 -g -i host/main.d -of=bin/voxelman.exe $DEPS $LIBS $LINKFLAGS
